usr/bin/asusd usr/bin/asusd
usr/bin/asusd-user usr/bin/asusd-user
usr/lib/systemd/system/asusd.service usr/lib/systemd/system/asusd.service
usr/lib/systemd/user/asusd-user.service usr/lib/systemd/user/asusd-user.service
usr/lib/udev/rules.d/99-asusd.rules usr/lib/udev/rules.d/99-asusd.rules
usr/share/asusd/* usr/share/asusd
usr/share/dbus-1/system.d/asusd.conf usr/share/dbus-1/system.d/asusd.conf
