Description: <short summary of the patch>
 TODO: Put a short summary on the line above and replace this paragraph
 with a longer explanation of this change. Complete the meta-information
 with other relevant fields (see below for details). To make it easier, the
 information below has been extracted from the changelog. Adjust it or drop
 it.
 .
 asusctl (6.0.12) oracular; urgency=medium
 .
   * New upstream release.
Author: Mitchell Augustin <mitchell@mitchellaugustin.com>

---
The information above should follow the Patch Tagging Guidelines, please
checkout https://dep.debian.net/deps/dep3/ to learn about the format. Here
are templates for supplementary fields that you might want to add:

Origin: (upstream|backport|vendor|other), (<patch-url>|commit:<commit-id>)
Bug: <upstream-bugtracker-url>
Bug-Debian: https://bugs.debian.org/<bugnumber>
Bug-Ubuntu: https://launchpad.net/bugs/<bugnumber>
Forwarded: (no|not-needed|<patch-forwarded-url>)
Applied-Upstream: <version>, (<commit-url>|commit:<commid-id>)
Reviewed-By: <name and email of someone who approved/reviewed the patch>
Last-Update: 2024-12-13

--- asusctl-6.0.12.orig/Cargo.toml
+++ asusctl-6.0.12/Cargo.toml
@@ -34,6 +34,9 @@ default-members = [
     "cpuctl",
     "rog-control-center",
 ]
+exclude = [
+    "vendor/",
+]
 
 [workspace.dependencies]
 tokio = { version = "^1.39.0", default-features = false, features = [
